### PR TITLE
Update Google Play and F-Droid badges

### PR DESCRIPTION
**Pull request by relan**
See [here](https://github.com/relan/androidclient/blob/badges/README.md) how those badges look on the page.

I've increased images to a somewhat standard size. Let me know if you prefer them to be smaller.

### CODE REVIEW

**Comment by daniele-athome** [comment]
They are perfect, thank you!

**Comment by relan** [comment]
> They are perfect

Glad to hear that because I'm the author of current F-Droid logo and badge. :)

**Comment by webratte** [comment]
@relan What do you think to make the same for www.kontalk.org ? 

Maybe you could also create a Logo for Desktop Client download on Kontalk.org.l

It's just a idea 😉

**Comment by daniele-athome** [comment]
@webratte I think some modifications to the kontalk.org website would be better than just including another logo. Since Kontalk is starting to be multiplatform (well, just 2 platforms for now), I'd be more inclined to create something like Telegram home page or WhatsApp download page.

**Pull request merged**
