### PR TITLE
Drawables improvements

### PR DESCRIPTION
**Pull request by relan**
Before and after:

screenshot-before1 screenshot-after1
screenshot-before2 screenshot-after2
screenshot-before5 screenshot-after5
screenshot-before3 screenshot-after3
screenshot-before4 screenshot-after4

The icons are from [Google material icon set](https://design.google.com/icons/). Dark icons have 54% opacity (#000000) as recommended by the [spec](http://www.google.com/design/spec/style/icons.html#icons-system-icons).

The size of APK decreased by 23 KB (thanks to `optipng` and unused resources removal).

### CODE REVIEW

**Comment by daniele-athome** [comment]
Thanks! I'll review it tonight.

**Comment by daniele-athome** [comment]
Thank you, great work!

**Comment by TheLastProject** [comment]
Can there be something added about the license of those icons being CC-BY later, perhaps in the README or so? We shouldn't create more #571s.

**Comment by webratte** [comment]
@relan Thank you. I like the new icons :+1:

**Pull request merged**
