### PR TITLE
Improve balloons sharpness

### PR DESCRIPTION
**Pull request by relan**
Provide 9-patch images for screen densities up to XXXDPI.

Before and after on a 560 dpi screen:

hangout-beforehangout-after
classic-beforeclassic-after
classicold-beforeclassicold-after
iphone-beforeiphone-after

### CODE REVIEW

**Comment by relan** [comment]
This change increased APK size by only 65 KB.

**Comment by daniele-athome** [comment]
Great work! Thanks @relan.

**Comment by relan** [comment]
BTW, I have those images in a vector format (Inkscape SVG). I think it's a good idea to upload them somewhere so that anyone could improve them. Is there a repository for artwork sources or something like that?

**Comment by daniele-athome** [comment]
Sure! I've added the `artwork/themes` directory, please create a PR adding the SVG files in that folder, you can use whatever naming convention you see fit, as long as anyone can easily link them to the actual themes in the app. Thanks!

**Pull request merged**
