### PR TITLE
Private key transfer

### PR DESCRIPTION
**Pull request by daniele-athome**
Use the session channel to deliver the private key safely to another device.

Server: kontalk/tigase-extension#85

### CODE REVIEW

**Comment by daniele-athome** [comment]
@abika I finished the implementation and I did some modifications to your code too. Particularly, I had to also receive the public key along with the private key because the public key contains the signature that is needed to actually login. The public key is not uploaded though, it is automatically returned by the server along with the private key (since the server has a copy).
Feel free to tell me comments or remarks about the procedure and the code in general.

Needless to say, the new code still requires massive testing. I might publish it on the Google Play alpha channel.

**Comment by webratte** [comment]
It seems this https://github.com/kontalk/androidclient/issues/122 is closed by this.

**Comment by daniele-athome** [comment]
You're right, thanks!

**Comment by abika** [comment]
Thanks for your work Daniele! I will look into it and implement the key transfer on the Desktop-Client side. Seems like I already started some of it two years ago to make the integration in the import wizard easier - although I can't remember doing so.)
This will definitely be done but I totally lack the time recently so it won't be finished soon...

**Comment by daniele-athome** [comment]
Don't worry, no rush.
I'll use this time to update the spec page: https://github.com/kontalk/specs/blob/master/account.md

**Comment by daniele-athome** [comment]
[I've updated the specs page with the protocol](https://github.com/kontalk/specs/commit/1eef3d09a9f55ba53db3df57051c437911b202b3). The `Account` class for private key retrieval is in [client-common-java](https://github.com/kontalk/client-common-java/blob/master/src/main/java/org/kontalk/client/Account.java). For uploading the key you can use a plain Data Form (don't ask me why I used a custom element for the retrieval part, I don't really remember).

The private key will be encrypted so you should ask for the passphrase before trying to import it.
For the moment, trust information is not included in the transferred data: there is just 1 private key packet and 1 public key packet (but it is enough to login: you'll need to generate the X.509 bridge certificate).

**Pull request merged**
