### PR TITLE
Fix German translation

### PR DESCRIPTION
**Pull request by hartwork**
Hi there!

I used Kontalk for the first time today and noticed a few glitches with the German translation.
I fixed only things that seem non-controversial to me. (There are more things one could fix, once it has been decided, if non-sentences should have commas added, too. I wasn't sure if that's a feature or a bug.)

Thanks and best, Sebastian

### CODE REVIEW

**Comment by webratte** [comment]
Hi @hartwork,
I'm one of the german translater.
Great to see another supporter.
Thanx for fixing my mistakes. :-)

But better to change the source Code and send a PR is fix it on http://translate.kontalk.org/

You can create a account and fix it on your own or just make a  suggestion and I will check and change it.

**Comment by hartwork** [comment]
Hello @webratte, thanks for the hint on https://translate.kontalk.org/. Is it a must or an if-you-like to use that website? Do I have to do the work once more to get the fixes in?

**Comment by webratte** [comment]
I think using weblate is better because changes in source code will not update the strings in weblate.

And I belive @daniele-athome (the developer) prefere this way to.

**Comment by daniele-athome** [comment]
Thanks for the contribution! I'll accept this PR for this time, but please consider creating an account on our translation portal.

**Comment by hartwork** [comment]
That's a good deal, thank you!

**Pull request merged**
