### PR TITLE
move translations from fdroiddata into Triple-T layout

### PR DESCRIPTION
**Pull request by eighthave**
Since app store translations are already being maintained here in Kontalk, it does not make sense to also maintain translations in fdroiddata. So this moves all the translations from there to here.  F-Droid will pick up these translations from the Kontalk git then.

Also, Kontalk already uses Weblate.  There is a new feature in Weblate that lets you add the Triple-T Gradle Play Publisher files directly to Weblate, instead of needed a JSON translation layer.
https://github.com/WeblateOrg/weblate/issues/1525#issuecomment-464852310

### CODE REVIEW

**Comment by eighthave** [comment]
The tests are failing because they require a release key, which my fork doesn't have:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:packageBasicRelease'.
> SigningConfig "release" is missing required property "storePassword".
```

**Comment by daniele-athome** [comment]
Thanks! I'll have a look and merge it as soon as I can.

Thanks for the heads-up about Triple-T support in Weblate. We'll have it on Weblate next release.

**Comment by eighthave** [comment]
any chance of tagging a release with this in it?

**Comment by daniele-athome** [comment]
I'm currently testing 4.3.0 (in a private alpha), so I guess it will happen soon enough.

**Pull request merged**
