### PR TITLE
Material design

### PR DESCRIPTION
**Pull request by daniele-athome**
Time for a new user interface :-)

- [x] styles
  - [x] styles
  - [x] styles (v11)
  - [x] ldpi
- [x] migration from ActionBar to Toolbar
  - [x] toolbar with subtitle
  - [x] progress bar indeterminate (turn into circular progress)
- [x] material dialogs
- [x] remove icons from dialogs
- [x] remove title from dialogs when not needed
- [x] convert dialog title to question when needed
- [x] rename positive buttons to actual action names
- [x] floating action button (create + remove menu item)
- [x] point user to floating action button (res: text_conversations_empty)
- [x] material progress dialogs
  - [x] connecting to google play iab
  - [x] registering to kontalk
  - [x] upgrading from 2.x
  - [x] use of LockedProgressDialog ~~(pull request for onSearchRequested)~~
  - [x] deleting account
  - [x] updating serverlist
- [x] remove useless ok buttons from dialogs
- [x] input dialog
- [x] password input dialog
- [x] audio message seekbar is 120dp fixed
- [ ] Froyo/Gingerbread compatibility
  - [ ] conversation item slightly moving to the right upon action mode selection
  - [ ] floating action button blank image
- [x] authenticator activities
- [x] circle avatars
  - [x] ensure same width for all pictures
  - [x] initials-based pictures
- [x] self avatar for outgoing messages
- [ ] use initials-based avatar for outgoing picture if none available
- [x] self avatar click should open own profile quick view if possible (API v14+, use self number lookup if found on older versions)
- [x] click on toolbar goes to contact
- [x] preferences
- [x] preferences (privacy fragment)
- [ ] preference category headers (https://github.com/jenzz/Android-MaterialPreference - not enough though)
- [ ] drop pre-v11 composer bar?
- [x] attachment selector
- [ ] text placeholder for missing media files (e.g. Image: image/jpg)
- [x] balloons with avatars
  - [x] hangout 9patches
  - [x] new theme should be used by default?
  - [x] older themes doesn't have avatars by their sides
- [x] new notification API
- [x] multiselect and contextual action bar (needs pre-v11 implementation, e.g. https://github.com/akalipetis/action-mode-list-fragment/)
  - [x] conversations
  - [x] messages
  - [x] click events pass through (http://stackoverflow.com/q/28877708/1045199)
- [ ] search button on v10-ldpi has no effect (WHAT!?!?)
- [x] after tapping a notification, the avatar shown in the conversation may be from the person in the last nofication you chatted to instead of from this one (might be related to the newly introduced onNewIntent management)
- [x] Android 5.1: with input method open, emoji drawers covers input field
- [x] app/src/main/AndroidManifest.xml:0:0 Error:
        uses-sdk:minSdkVersion 8 cannot be smaller than version 9 declared in library app/build/intermediates/exploded-aar/de.hdodenhof/circleimageview/1.3.0/AndroidManifest.xml
        Suggestion: use `tools:overrideLibrary="de.hdodenhof.circleimageview"` to force usage (hdodenhof/CircleImageView#67)
- [x] icons
- [x] build tools 23 + appcompat 23 (and deprecated HttpClient)
- [x] https://github.com/kontalk/androidclient/pull/412#issuecomment-133193253
- [x] tablet UI
- [x] new message status icons
- [x] new application icon
- [ ] search bar
- [ ] compose message list: use inset overlay scroll bars?
- [x] New material balloons #551
- [x] outgoing balloons width issue
- [ ] tiled default background
- [ ] indexed scrolling in contacts list
- [ ] layout performance optimizations (especially in message list)
- [ ] accessibility fixes (e.g. contentDescription)
- [ ] final clean

### CODE REVIEW

**Comment by webratte** [comment]
@daniele-athome What means "Use profile photo for outgoing messages"
Is this like in WhatsApp that my profile photo is sendet to receiver like in WhatsApp?
I hate this featre :-1:

**Comment by daniele-athome** [comment]
>  Is this like in WhatsApp that my profile photo is sendet to receiver like in WhatsApp?

No, it's just a UI thing. It shows your own profile picture (usually what you set in Gmail/G+ account) in the chats for outgoing messages (much like Hangouts does IIRC). Profile information is for API level 14 up, so older Android will get the usual "unknown photo" picture.

**Comment by webratte** [comment]
Thank you.
Nice to read that :-)

**Comment by TheLastProject** [comment]
Just repeating the issues I ran into on this branch. The first three are **regressions** from 3.0.1
- [ ] Personal key import fails, you are never asked to enter a password
- [ ] I got a crash when clicking a notification. Once doing so quickly after sending a message, once while I was manually syncing my contact list
- [ ] Somehow, sending a message after your personal key changed caused **them** to get an (encrypted) message. I can't explain it, but at least 4 people reported this to me.
- [ ] The conversation overview allows you to scroll down further than there are conversations (the new chat button should just hide when scrolling down, perhaps reappear after some seconds to make it easier to find?)
- [ ] It would be nice if it would also generate icons for yourself if you miss a profile picture

**Comment by daniele-athome** [comment]
@TheLastProject would you produce a logcat for errors 1 and 2 please?

**Comment by TheLastProject** [comment]
@daniele-athome The logcat for error 1 only shows the following:
```
E/NumberValidation( 4101):      at org.kontalk.ui.InputDialog$Builder.build(InputDialog.java:54)
E/NumberValidation( 4101):      at org.kontalk.ui.NumberValidation.importAskPassphrase(NumberValidation.java:662)
E/NumberValidation( 4101):      at org.kontalk.ui.NumberValidation.access$500(NumberValidation.java:101)
E/NumberValidation( 4101):      at org.kontalk.ui.NumberValidation$5.onClick(NumberValidation.java:637)
```
I am not willing to try to get a logcat for error 2 until I can import my private key so I do not have to bother people with another key change.

**Comment by daniele-athome** [comment]
> @daniele-athome The logcat for error 1 only shows the following:

I think the stacktrace is not complete. Where is the exception?

**Comment by TheLastProject** [comment]
@daniele-athome That is the output of `adb logcat | grep kontalk` from the moment I choose "key import" to the moment I get the failed to import error. Should I filter some other way? A filter is going to be necessary anyway, because of the huge amount of log events generated on Android by all the apps.

**Comment by daniele-athome** [comment]
That's not enough I'm afraid. Download this and make it executable: https://raw.githubusercontent.com/jasta/android-dev-tools/master/proclogcat

Execute it this way:

```
adb logcat -d | proclogcat org.kontalk >logcat.txt
```

It will print out (and exit) the whole log from process org.kontalk.

**Comment by TheLastProject** [comment]
```
I/dalvikvm( 1964): Could not find method android.view.ViewGroup.<init>, referenced from method com.afollestad.materialdialogs.internal.MDRootLayout.<init>
W/dalvikvm( 1964): VFY: unable to resolve direct method 9600: Landroid/view/ViewGroup;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
D/dalvikvm( 1964): VFY: replacing opcode 0x70 at 0x0001
I/dalvikvm( 1964): Could not find method android.widget.TextView.<init>, referenced from method com.afollestad.materialdialogs.internal.MDButton.<init>
W/dalvikvm( 1964): VFY: unable to resolve direct method 10285: Landroid/widget/TextView;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
D/dalvikvm( 1964): VFY: replacing opcode 0x70 at 0x0000
E/NumberValidation( 1964): error importing keys
E/NumberValidation( 1964): java.lang.NullPointerException
E/NumberValidation( 1964):      at org.kontalk.ui.InputDialog$Builder.build(InputDialog.java:54)
E/NumberValidation( 1964):      at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1158)
E/NumberValidation( 1964):      at org.kontalk.ui.NumberValidation.importAskPassphrase(NumberValidation.java:662)
E/NumberValidation( 1964):      at org.kontalk.ui.NumberValidation.access$500(NumberValidation.java:101)
E/NumberValidation( 1964):      at org.kontalk.ui.NumberValidation$5.onClick(NumberValidation.java:637)
E/NumberValidation( 1964):      at com.afollestad.materialdialogs.AlertDialogWrapper$Builder$3.onPositive(AlertDialogWrapper.java:202)
E/NumberValidation( 1964):      at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:321)
E/NumberValidation( 1964):      at android.view.View.performClick(View.java:4204)
E/NumberValidation( 1964):      at android.view.View$PerformClick.run(View.java:17355)
E/NumberValidation( 1964):      at android.os.Handler.handleCallback(Handler.java:725)
E/NumberValidation( 1964):      at android.os.Handler.dispatchMessage(Handler.java:92)
E/NumberValidation( 1964):      at android.os.Looper.loop(Looper.java:137)
E/NumberValidation( 1964):      at android.app.ActivityThread.main(ActivityThread.java:5041)
E/NumberValidation( 1964):      at java.lang.reflect.Method.invokeNative(Native Method)
E/NumberValidation( 1964):      at java.lang.reflect.Method.invoke(Method.java:511)
E/NumberValidation( 1964):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/NumberValidation( 1964):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/NumberValidation( 1964):      at dalvik.system.NativeStart.main(Native Method)
```

**Comment by daniele-athome** [comment]
Thanks @TheLastProject, I'll check it later.

**Comment by TheLastProject** [comment]
- [ ] Upon selecting a thread in the thread list, the time and receiving status jumps slightly to the right, out of place with other time/status notices.

**Comment by daniele-athome** [comment]
> Upon selecting a thread in the thread list, the time and receiving status jumps slightly to the right, out of place with other time/status notices.

Yes, I noticed it while testing in an API 10 emulator. That's going to be tough because that's probably a manifestation of a weird layout behaviour - probably because of appcompat, but I don't want to point fingers just yet.

**Comment by daniele-athome** [comment]
And I think that's your crash on notification click:

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
     at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1377)
     at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1395)
     at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:637)
     at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:616)
     at org.kontalk.ui.ComposeMessage.onNewIntent(ComposeMessage.java:426)
     at org.kontalk.ui.ComposeMessage.onNewIntent(ComposeMessage.java:411)
     at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1184)
     at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2329)
     at android.app.ActivityThread.performNewIntents(ActivityThread.java:2342)
     at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2351)
     at android.app.ActivityThread.access$1600(ActivityThread.java:139)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:136)
     at android.app.ActivityThread.main(ActivityThread.java:5086)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by h-2** [comment]
Is this the place to humbly ask for a dark theme again? Or is this difficult to do with material design? Thank you :)

**Comment by daniele-athome** [comment]
@h-2 it will be probably be easier actually using material. I'll include it in the todo list :-)

**Comment by TheLastProject** [comment]
Here we go again, not sure all of these are Material, this time on an Android 5.1.1 (CyanogenMod 12.1 device):
- [ ] On the conversation lists, the compose button hits the bottom right edge of the screen. There should be some padding
- [ ] In a conversation, the scrollbar on the right always appears, even when not scrolling, and doesn't extend to the top properly (there is a gap between the top bar and the scroll bar, but not between the bottom bar and the scroll bar)
- [ ] Clicking your own avatar selects the message, but clicking the contact avatar opens contact information. This is probably not a true bug, but very inconsistent behaviour
- [ ] Tapping the mic button in a conversation shows "Error starting audio recording."

I also can not reproduce https://github.com/kontalk/androidclient/pull/412#issuecomment-121725895 on this device, but seeing how you found it in an emulator I'll leave it unchecked.

**Comment by daniele-athome** [comment]
@TheLastProject please I need stacktraces for the import key error you mentioned on IRC and for the audio recording error.
Also when you will be able to make screenshots, a screenshot of bug 2 would be helpful.

**Comment by TheLastProject** [comment]
I have updated the previous comment

**Comment by h-2** [comment]
> it will be probably be easier actually using material. I'll include it in the todo list :-)

great, thanks!

**Comment by TheLastProject** [comment]
- [ ] In the conversation and new chat view, the scrollbar on the right is in a different style than on other screens
screenshot_2015-07-20-22-57-15

**Comment by TheLastProject** [comment]
- [ ] When clicking the smiley button with the keyboard open, the smiley selector goes on top of the input area (Android 5.1.1, CyanogenMod 12.1). This does not happen when the smiley button is pressed while the keyboard is closed  
screenshot_2015-07-21-19-02-07

**Comment by TheLastProject** [comment]
Hard to see but...
- [ ] If a long message ends with a smiley, the smiley gets appended after the elipsis (only on outgoing messages)  
smileyappend

**Comment by webratte** [comment]
@TheLastProject It seems you are very interested in technology. And you're have some skills like read loggs and compile sourcecode. Have you ever thought about learning developing?
I think it would be very helpfully if you could fix easy and not so important things. 

Be sure this is not a joke and no sarcasm.

I'm to stupid for this things :-(

Sorry for off topic!

**Comment by TheLastProject** [comment]
I am currently unable to compile Kontalk as the device I am using currently has overheating issues. I will definitely give Android development another try when I can use a device that doesn't overheat.

On 21 July 2015 22:16:43 CEST, webratte <notifications@github.com> wrote:
>@TheLastProject It seems you are very interested in technology. And
>you're have some skills like read loggs and compile sourcecode. Have
>you ever thought about learning developing?
>I think it would be very helpfully if you could fix easy and not so
>important things. 
>
>Be sure this is not a joke and no sarcasm.
>
>I'm to stupid for this things :-(
>
>Sorry for off topic!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/pull/412#issuecomment-123465437

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by abika** [comment]
You can always run Android on an emulated device, very simple with Android SDK/Android studio

**Comment by TheLastProject** [comment]
I'm trying to not use proprietary software, which makes setting up emulation very, very tough. And ever then, it would still cause overheating issues. It doesn't keep me from having to compile. Still, thanks for the hint.

**Comment by abika** [comment]
oh, I thought you meant your phone, not your pc. Im a bit tired...

**Comment by TheLastProject** [comment]
- [ ] After tapping a notification, the avatar shown in the conversation may be from the person in the last nofication you chatted to instead of from this one (not sure how to reproduce yet)

**Comment by daniele-athome** [comment]
> After tapping a notification, the avatar shown in the conversation may be from the person in the last nofication you chatted to instead of from this one (not sure how to reproduce yet)

I think I know why this happened... I should have fixed that in master and merged it to material recently... I'll double-check it just to be sure. I don't remember if you have that fix in your apk though.

**Comment by TheLastProject** [comment]
- [ ] Messages are drawn slightly too far to the right on initial load, causing the image circle to be cut off
screenshot_2015-08-21-00-00-15

The message is redrawn correctly when scrolling the message out of view and then back into view, which is why the last outgoing message is drawn correctly (I scrolled up and down again before taking this screenshot). I assume that, on first draw, the scrollbar is not calculated in.

On my screen, the incorrectly drawn avatars start 77 pixels from the left, the correctly drawn avatars start 84 pixels from the left (+/- some small mistakes caused by calculating by reading mouse coordinates off the image on my desktop)

**Comment by daniele-athome** [comment]
First crash on tablets... expected, tablet hasn't been tested yet.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewStub.setLayoutResource(int)' on a null object reference
at org.kontalk.ui.view.BaseMessageTheme.inflate(BaseMessageTheme.java:60)
at org.kontalk.ui.view.AvatarMessageTheme.inflate(AvatarMessageTheme.java:55)
at org.kontalk.ui.view.MessageListItem.afterInflate(MessageListItem.java:128)
at org.kontalk.ui.adapter.MessageListAdapter.newView(MessageListAdapter.java:107)
at android.widget.CursorAdapter.getView(CursorAdapter.java:250)
at android.widget.AbsListView.obtainView(AbsListView.java:2828)
at android.widget.ListView.makeAndAddView(ListView.java:1902)
at android.widget.ListView.fillUp(ListView.java:749)
at android.widget.ListView.layoutChildren(ListView.java:1689)
at android.widget.AbsListView.onLayout(AbsListView.java:2632)
at android.view.View.layout(View.java:16763)
at android.view.ViewGroup.layout(ViewGroup.java:5333)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
```

**Comment by h-2** [comment]
**1.** right now the dialog-boxes in hangouts-style are way bigger than the content, i.e.
```
+-------------------+->
|                :) |
+-------------------+
```
I think it would look a lot better if they were adapted to short messages:
```
             +------+->
             |   :) |
             +------+
```


**2.** Also, what do you think about a drawer? Or whatever these things are called that you can swipe in from the left? I think it would be really cool, if there was a drawer and it included all the points that are currently behind the "menu"-button. Then instead of the menu-button you could show the current connected/disconnected status of Kontalk!

**3.** And if inside a chat, a left-to-right swipe should bring you back to the main screen I think!

But all-in-all I like the interface, very "modern"!

**Comment by h-2** [comment]
> Then instead of the menu-button you could show the current connected/disconnected status of Kontalk!

Or one could have the status field be in the top right corner and editable.

**Comment by h-2** [comment]
other unimportant minor things I noticed:
  * would be nice if the bar at the top had a small drop-shadow!
  * the circular contact avatars could be a little bigger :)

**Comment by daniele-athome** [comment]
> Messages are drawn slightly too far to the right on initial load, causing the image circle to be cut off

Thanks @TheLastProject, I'll look into it.

> right now the dialog-boxes in hangouts-style are way bigger than the content

Before Google changed it they were full-width IIRC. I guess they switched back to shrinker balloons :-)
I'll do some experiments.

> Also, what do you think about a drawer?

We recently introduced (soon to be released 3.0.5 and 3.1-beta3) a sliding pane layout which contains what is now the contacts list activity (more info here in #543).

> And if inside a chat, a left-to-right swipe should bring you back to the main screen I think!

Ooooh I hate that :P
> would be nice if the bar at the top had a small drop-shadow!

Do you mean the toolbar (the activity title bar) or the "warning message" bar?

> the circular contact avatars could be a little bigger :)

I'm trying to follow material design specs here, sorry.

**Comment by webratte** [comment]
Don't forget this issue ;-)

Inpufield dissapaers behind keyboard #542

**Comment by webratte** [comment]
Phone: HTC desire X
Android: 4.1.1
Kontalk: 3.1-beta3

On Hanout theme text is cut off on the left side.

See also the screenshot
screenshot

**Comment by daniele-athome** [comment]
Thanks @webratte, I'll look into it.

**Pull request merged**
