### PR TITLE
Add balloons images sources

### PR DESCRIPTION
**Pull request by relan**
Inkscape SVG format, MDPI scale.

### CODE REVIEW

**Comment by daniele-athome** [comment]
Thanks! What's the license for these files? I'll update the artwork and main READMEs.

**Comment by relan** [comment]
> Thanks! What's the license for these files? I'll update the artwork and main READMEs.

I think CC-BY-SA is the best choice for a GPL project.

**Comment by daniele-athome** [comment]
I've introduced "message blocks": adjacent messages from the same sender, much like Hangouts itself (so only for the Hangouts theme). Commit is 1b237e2.
I've been meaning to ask you @relan, would you build new drawables for both incoming and outgoing [like in the example](https://github.com/kontalk/androidclient/blob/master/app/src/main/res/drawable-xhdpi/balloon_hangout_block_incoming.9.png) (did it by hand, to be thrown away :-)) following these rules (also tell me what you think):

* "starting" balloons (the ones starting the block) should have upper margin only (no lower margin so they can be "closer" to the non-starting balloons)
* "continuation" balloons (the ones after the first one) should have no upper and lower margins so they seem closer to each other (to give the feeling of continuation)

This is only for the Hangouts theme. I know, it's a crap explaination. Please ask if you need more details. Of course no rush, no nothing, just a humble request :-) thank you.

**Comment by relan** [comment]
I'm ready to help with this. So, the new Hangouts theme should consist of 4 drawables:

1. "In" starting.
2. "In" continuing.
3. "Out" starting.
4. "Out" continuing.

Something like this:

kontalk-adjacent-balloon

Did I understand you correctly? I've never used Hangouts and don't have Gapps to check how it looks. Official screenshots aren't useful either.

**Comment by daniele-athome** [comment]
You understood perfectly! Thanks!

**Comment by daniele-athome** [comment]
Just to be clear: only for the Hangouts theme for now. Other themes don't have avatars so this really doesn't apply.

**Comment by daniele-athome** [comment]
I've merged #807 with modifications for the top/bottom gravity (I couldn't use your solution because other margins were involved, sorry). You might incur in some conflicts with this PR though. Contact me if you need help.

**Comment by daniele-athome** [comment]
Another note: Silence does repeat avatars for every message (see https://play.google.com/store/apps/details?id=org.smssecure.smssecure), so the "message grouping" thing doesn't apply either.

**Comment by relan** [comment]
Added drawables in #815 and updated SVGs in this PR. Let me know if something should be amended.

**Comment by daniele-athome** [comment]
Hey @relan, I'd like to add you to the credits, what do you think? If you want I can put you in the app credits screen, with whatever name and contact information (e-mail or whatever you want, even nothing) you wish.

**Comment by relan** [comment]
I'd be very pleased to be mentioned in such a great project! My real name is Andrew Nayenko.

I prefer to keep my email unpublished. Let me know if you need my email for any private discussions.

**Comment by daniele-athome** [comment]
Thanks! For now I've added you to the graphics/icons section (3114ade) but since you also contributed to some code I'll insert you among the contributors as well (#828).

**Comment by daniele-athome** [comment]
Hey @relan how are you doing? It would be nice if you can participate in our new forum, [this discussion](https://forum.kontalk.org/t/colours-for-silence-chat-bubble-layout/219/3) in particular, what do you think?

**Comment by relan** [comment]
Fine, thanks! :)

I think it's better to set balloons color at run time using `setColorFilter()` method. It can even be user-configurable.

**Comment by daniele-athome** [comment]
Thanks, I'll do some tests with it.

**Pull request merged**
