### PR TITLE
Add block balloons for the Hangout theme

### PR DESCRIPTION
**Pull request by relan**
Commit 1b237e2 introduced "continuation" balloons for sequential messages. Add drawables for those balloons and remove bottom paddings from the "starting" balloons.

Other themes are intact.

### CODE REVIEW

**Comment by daniele-athome** [comment]
You're the best! :-)
There is only one small thing (don't kill me): did you use the same 9-patch markers? The content upper padding seems smaller than before.

**Comment by relan** [comment]
> did you use the same 9-patch markers? The content upper padding seems smaller than before.

I've corrected them a bit to make more balanced. I can restore previous paddings if you wish.

**Comment by daniele-athome** [comment]
It gave me a feeling of not being symmetric... Besides, watching Hangouts, the upper padding is bigger than the lower padding (not measured, just watched). Please restore previous paddings. Thanks!

**Comment by daniele-athome** [comment]
Wait I just realized that I apply some padding myself in the layout. Let me do some checks, I'll get back to you soon.

**Comment by daniele-athome** [comment]
I've handled the margins within the layouts, I realized you were right: 9-patch should be symmetric in any way in this case, extra margins and paddings can be handled in layouts. Thanks!

**Comment by relan** [comment]
Thanks for being pedantic. All those tiny things do matter.

**Comment by webratte** [comment]
@relan Great work. I like this feature :+1:

**Comment by daniele-athome** [comment]
@relan https://github.com/kontalk/androidclient/issues/179#issuecomment-247969769 (I don't know if you got a notification)

**Pull request merged**
