### PR TITLE
Add Silence theme

### LINKED ISSUE #656: Add Signal/SMSSecure balloon theme

### PR DESCRIPTION
**Pull request by relan**
Based on @mimi89999's work. Increases APK size by 6 KB. Fixes #656.

### CODE REVIEW

**Comment by daniele-athome** [comment]
Thanks @relan, great work as usual :-)
However we need to address the avatar alignment issue. It should be aligned to the bottom of the balloon for incoming messages because of how the balloon image is made. And only for this theme. You could either:

* create a new child class of AvatarMessageTheme that changes the gravity of the avatar from "start" to "end" directly from code (calling it something like LowerAvatarMessageTheme or something meaningful, for generic use also for other lower-avatar-based themes)
* create a new layout identical to balloon_avatar_in with the gravity of the avatar changed from "start" to "end"
* any other ideas?

Also, why did you have to create two distinguished instance creations for incoming and outgoing messages in the theme factory? AvatarMessageTheme already handles outgoing messages without avatar (much like the Hangouts theme).

Thanks for your contribution!

**Comment by relan** [comment]
I've addressed your second comment.

Avatar alignment issue is more complex than I thought. Probably the best solution is to create two `balloon_avatar_in` layouts (top- and bottom-aligned) and move their common XML code into an include.

**Comment by daniele-athome** [comment]
Perfect! Thank you. I'll deal with the first issue myself.

**Comment by relan** [comment]
OK.

// Added SVG sources.

**Pull request merged**
